#!/usr/bin/perl -w
# See bottom of file for license and copyright information
#
# The Foswiki 'bin' directory must be on your include path when you run
# this script. This is so it can pick up the right environment
# from setlib.cfg.
# You can add a directory to your include path using the -I option
# to the perl command e.g. perl -I /usr/local/foswiki/bin tick_foswiki.pl
#
# It executes a number of non-essential regular administration
# tasks that will help keep your Foswiki healthy and happy.
#
# It is intended to be run as a cron job (remember it has to be run
# by a user who can write files created by the webserver user!)
# For example,
#
# 0 0 * * * (cd /usr/foswiki/bin && ./tools/virtualhost-tick-foswiki)
#
use strict;
use warnings;

BEGIN {
    $Foswiki::cfg{Engine} = 'Foswiki::Engine::CLI';
    if ( -e './setlib.cfg' ) {
        unshift @INC, '.';
    }
    elsif ( -e '../bin/setlib.cfg' ) {
        unshift @INC, '../bin';
    }    # otherwise rely on the user-set path
    require 'setlib.cfg';
}

use Foswiki ();
use Foswiki::LoginManager ();
use Foswiki::Request::Cache ();
use Foswiki::Meta ();
use Foswiki::Contrib::VirtualHostingContrib::VirtualHost ();

my $verbose = 0;
my $hostname = '';

foreach my $arg (@ARGV) {
  if ($arg =~ /^(.*)=(.*)$/) {
    if ($1 eq 'verbose') {
      $verbose = ($2 eq 'on')?1:0;
    } elsif ($1 eq 'host') {
      $hostname = $2;
    }
  }
}

if ($hostname) {
  Foswiki::Contrib::VirtualHostingContrib::VirtualHost->run_on($hostname, \&doit);
} else {
  Foswiki::Contrib::VirtualHostingContrib::VirtualHost->run_on_each(\&doit);
}

sub doit {
  printf("=> Processing %s\n", $Foswiki::Contrib::VirtualHostingContrib::VirtualHost::CURRENT) if $verbose;
  Foswiki::LoginManager::expireDeadSessions();
  Foswiki::Request::Cache::cleanup();
  my $root = new Foswiki::Meta( new Foswiki() );
  $root->onTick( time() );
}

__END__
Foswiki - The Free and Open Source Wiki, http://foswiki.org/

Copyright (C) 2009-2012 Foswiki Contributors. Foswiki Contributors
are listed in the AUTHORS file in the root of this distribution.
NOTE: Please extend that file, not this notice.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version. For
more details read LICENSE in the root of this distribution.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

As per the GPL, removal of this notice is prohibited.

